services:
  my-nginx-service:
    image: nginx
  web:
    build:
      context: .
      dockerfile: dockerfile
    ports:
     - "8080:8080"
    env_file:
     - .env
    environment:
     - PORT=8080
    volumes:
     - r2k8s:/app/data
  my-redis-service:
    image: redis
    volumes:
      - myredisdata:/data
volumes:
  r2k8s:
  myredisdata:

