name: Compose - Build Push & Deploy
on:
  workflow_dispatch:
jobs:
  build-push-deploy:
    runs-on: ubuntu-latest
    env:
      DH_USER: ${{ secrets.DOCKERHUB_USERNAME }}
      REPO: ${{ secrets.DOCKERHUB_REPO }}
      SSH_OPT: "-o StrictHostKeyChecking=no"
      REMOTE: "root@${{secrets.AKAMAI_INSTANCE_IP}}"
      REMOTE_APP_DIR: './opt/app'
    steps:
    - name: Check out actions
      uses: actions/checkout@v4
    - name: Docker Authentication
      uses: docker/login-action@v3.6.0
      with:
          username: "${{ secrets.DOCKERHUB_USERNAME }}"
          password: "${{ secrets.DOCKERHUB_PAT}}"
    - name: Build Container
      run: |
        docker build -f dockerfile \
        -t "$DH_USER/$REPO:latest" \
        -t "$DH_USER/$REPO:${{ github.sha }}" \
        .
    - name: Push Container
      run: |
        docker push "$DH_USER/$REPO" --all-tags
    - name: Implement SSH Privacy
      run: |
        mkdir -p ~/.ssh/
        echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
        echo "Host ${{ secrets.AKAMAI_INSTANCE_IP }}" > ~/.ssh/config
        echo "StrictHostKeyChecking no" >> ~/.ssh/config
        chmod 600 ~/.ssh/id_rsa
    - name: Install Docker and Docker Compose on server
      run: |
        ssh root@172.236.233.238
        echo "Successful login to your VM"
