name: Run Ansible
on:
  workflow_dispatch:
jobs:
  run-playbooks:
    runs-on: ubuntu-latest
    steps:
    - name: Checking to checkout action
      uses: actions/checkout@v3
    - name: Setup Python 4
      uses: actions/setup-python@v4
      with:
          python-version: "3.8"
    - name: Upgrade pip and install Ansible
      run: |
        python -m pip install --upgrade pip
        python -m pip install ansible
    - name: Setup SSH
      run: |
        mkdir -p ~/.ssh/
        echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
        chmod 600 ~/.ssh/id_rsa
    - name: Implement Ansible inventory ini
      run: |
        mkdir -p ./devops/ansible
        export INVENTORY_FILE =./devops/ansible/inventory.ini
        echo "[my_host_group]" > $INVENTORY_FILE
        echo "${{ secrets.AKAMAI_INSTANCE_IP }}" >> $INVENTORY_FILE
    - name: Implement Ansible Configuration file
      run: |
        mkdir -p ./devops/ansible
        cat <<EOF > ./devops/ansible/ansible.cfg
        [defaults]
        ansible_python_interpreter = /usr/bin/python
        ansible_ssh_private_key_file = ~/.ssh/id_rsa
        remote_user = root
        inventory = ./inventory.ini
        host_key_checking = false
        EOF
    - name: Ping Ansible Hosts
      working-directory: ./devops/ansible
      run: |
        ansible all -m ping
    - name: Install nginx with Ansible
      working-directory: ./devops/ansible
      run: |
        ansible-playbook install-nginx.yaml
    - name: Deploy Python with Ansible
      working-directory: ./devops/ansible
      run: |
        ansible-playbook deploy-python.yaml

